"""updtaed  products  table

Revision ID: 4d6a381a85d7
Revises: 7a74dcc879bd
Create Date: 2025-12-02 10:35:52.641366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6a381a85d7'
down_revision: Union[str, None] = '7a74dcc879bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
